
package it.cineca.u_gov.co.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ApplicationException", targetNamespace = "http://ws.co.u-gov.cineca.it/")
public class ApplicationException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApplicationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ApplicationException_Exception(String message, ApplicationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ApplicationException_Exception(String message, ApplicationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.cineca.u_gov.co.ws.ApplicationException
     */
    public ApplicationException getFaultInfo() {
        return faultInfo;
    }

}
