
package it.cineca.u_gov.co.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws/private/service", targetNamespace = "http://ws.co.u-gov.cineca.it/", wsdlLocation = "https://www.uniud.u-gov.it/ws-co/ws/private/service?wsdl")
public class Ws_002fPrivate_002fService
    extends Service
{

    private final static URL WS_002FPRIVATE_002FSERVICE_WSDL_LOCATION;
    private final static WebServiceException WS_002FPRIVATE_002FSERVICE_EXCEPTION;
    private final static QName WS_002FPRIVATE_002FSERVICE_QNAME = new QName("http://ws.co.u-gov.cineca.it/", "ws/private/service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.uniud.u-gov.it/ws-co/ws/private/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WS_002FPRIVATE_002FSERVICE_WSDL_LOCATION = url;
        WS_002FPRIVATE_002FSERVICE_EXCEPTION = e;
    }

    public Ws_002fPrivate_002fService() {
        super(__getWsdlLocation(), WS_002FPRIVATE_002FSERVICE_QNAME);
    }

    public Ws_002fPrivate_002fService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS_002FPRIVATE_002FSERVICE_QNAME, features);
    }

    public Ws_002fPrivate_002fService(URL wsdlLocation) {
        super(wsdlLocation, WS_002FPRIVATE_002FSERVICE_QNAME);
    }

    public Ws_002fPrivate_002fService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS_002FPRIVATE_002FSERVICE_QNAME, features);
    }

    public Ws_002fPrivate_002fService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ws_002fPrivate_002fService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCOServiceService
     */
    @WebEndpoint(name = "WSCOServiceServicePort")
    public WSCOServiceService getWSCOServiceServicePort() {
        return super.getPort(new QName("http://ws.co.u-gov.cineca.it/", "WSCOServiceServicePort"), WSCOServiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCOServiceService
     */
    @WebEndpoint(name = "WSCOServiceServicePort")
    public WSCOServiceService getWSCOServiceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.co.u-gov.cineca.it/", "WSCOServiceServicePort"), WSCOServiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS_002FPRIVATE_002FSERVICE_EXCEPTION!= null) {
            throw WS_002FPRIVATE_002FSERVICE_EXCEPTION;
        }
        return WS_002FPRIVATE_002FSERVICE_WSDL_LOCATION;
    }

}
